production.c File Reference
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include `production.h`
#include <math.h>
Functions
bool production (int argc, char *argv[])
void print_days (int days_in_month, int day_of_week)
int calculate_days_in_month (int year, int month)
int is_leap_year (int year)
int calculate_day_of_week (int day, int month, int year)
void print_month (int month)
Function Documentation
calculate_day_of_week()
int calculate_day_of_week (int day, int month, int year)
Determines what day of the week a particular date falls on.
Parameters
day Day of the month, counting from 1.
month Range 0 through 11, where January = 0.
year The year.
Returns
-1 for invalid input (e.g., year < 1752, month out of range, day < 1 or > appropriate for that month & year 0 through 6, where Sunday = 0.
Referenced by production(), and testCalcDayOfWeek().
calculate_days_in_month()
int calculate_days_in_month (int year, int month)
Calculates how many days are in a given month for a given year.
Parameters
year The year we are checking.
month The month we are checking. Range 0 through 11, where January = 0.
Returns
Day of the week. Range 0 through 6, where Sunday = 0. -1 if invalid input (e.g., year < 1752, month out of range).
References is_leap_year().
Referenced by production(), and testCalcDaysInMonth().
is_leap_year()
int is_leap_year (int year)
Test if a given year is a leap year or not.
Parameters
year The year we are testing
Returns
1 if it is a valid leap year. 0 if a valid year, but not a leap year. -1 if not a valid year (i.e. before the calendar rule changed in 1752).
Referenced by calculate_days_in_month(), and testIsLeapYear().
print_days()
void print_days (int days_in_month, int day_of_week)
Prints out the days in each given month.
Parameters
days_in_month How many days are in a given month for a given year.
day_of_week The day of the week a particular date falls on.
Referenced by production().
print_month()
void print_month (int month)
Print the months for the calendar
Parameters
month The index of the month that needs to be printed. Range 0 through 11, where January = 0.
Referenced by production().
production()
bool production (int argc, char * argv[])
Your production code goes in this function.
Parameters
argc Number of words on the command line
argv Array of pointers to character strings representing the words on the command line.
Returns
true if Program was able to print a calendar. false if User entered bad input.
References calculate_day_of_week(), calculate_days_in_month(), print_days(), and print_month().
Referenced by main().